[tool.poetry]
name = "taura"
version = "2.0.0"
description = "Machine translation model for translating Kikuyu to English"
authors = ["James Wanjku <james544wanjiku@gmail.com>"]
readme = "README.md"
repository = "https://github.com/garnet-owl/taura-2.0"
license = "MIT"
packages = [{include = "app"}]

[tool.poetry.dependencies]
python = "^3.12"
numpy = "^2.2.4"
pandas = "^2.2.3"
pydantic = "^2.11.1"
scikit-learn = "^1.6.1"
tqdm = "^4.66.2"
nltk = "^3.9.1"
joblib = "^1.3.2"
loguru = "^0.7.3"
pyyaml = "^6.0.1"
click = "^8.1.7"
fasttext-wheel = "^0.9.2"

[tool.poetry.group.dev.dependencies]
pytest = "^8.0.2"
mypy = "^1.8.0"
pytest-cov = "^4.1.0"
pre-commit = "^3.6.2"
ruff = "0.11.5"

[tool.poetry.group.docs.dependencies]
sphinx = "^7.2.6"
sphinx-rtd-theme = "^2.0.0"

[build-system]
requires = ["poetry-core>=1.9.0"]
build-backend = "poetry.core.masonry.api"

[tool.mypy]
python_version = "3.8"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true
disallow_incomplete_defs = true

[tool.pytest.ini_options]
testpaths = ["app/tests"]
python_files = "test_*.py"
python_functions = "test_*"
python_classes = "Test*"
