# Basic linting configuration with only essential rules
lint.select = [
    "E",   # pycodestyle errors
    "F",   # pyflakes
]

# Never enforce certain rules
lint.ignore = [
    "E501",  # line too long
    "E741",  # ambiguous variable name
]

# Target Python version
target-version = "py312"

# Same line length as Black.
line-length = 88

# Ignore `E402` (import violations) in all `__init__.py` files.
[lint.per-file-ignores]
"__init__.py" = ["E402", "F401"]

# Configure formatter
[format]
# Like Black, use double quotes for strings.
quote-style = "double"

# Like Black, indent with spaces, rather than tabs.
indent-style = "space"

# Like Black, respect magic trailing commas.
skip-magic-trailing-comma = false

# Like Black, automatically detect the appropriate line ending.
line-ending = "auto"
